### ISSUE TITLE
Science Ores / Bottling / Dark Matter Replicators

### ISSUE THREAD

**Issue by awdwyn** [Leighzer/Factorio-Leighzers-Morphite#2]
Sorry - I don't know how to do pull requests or anything, but I've got recipe files for a few mods that I thought I'd share that work well.

science bottling: https://pastebin.com/sPcJB8A2
science ores: https://pastebin.com/9YmQBdgA
dark matter replicators: https://pastebin.com/KywjUJUD

I've also hacked support for this mod into my version of angels infinite ores and it works fantastic however I believe you need to contact arch666angel to have it officially added. https://mods.factorio.com/mod/angelsinfiniteores

**Comment by Leighzer** [comment]
Integrated into mod.
